// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/ui/theme-provider";
// import Header from "@/components/header";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";
// import { Toaster } from "sonner";
// // import { Toaster } from "@/components/ui/sonner";

// const inter=Inter({subsets:["latin"]})

// export const metadata = {
//   title: "InterView Yodha",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider appearance={{
//       baseTheme:dark,
//     }}>
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${inter.className}`}
//       >
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="dark"
//             enableSystem
//             disableTransitionOnChange
//           >
//             <Header />
//             <main className="min-h-screen">{children}</main>
//             <Toaster richColors />

//             <footer className="bg-muted/50 py-12 ">
//               <div className="container mx-auto px-4 text-center text-gray-200">
//                 <p>lorem</p>
//               </div>
//             </footer>
//           </ThemeProvider>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InterView Yodha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            <footer className="bg-muted/50 py-12">
              <footer className="bg-black text-gray-200 py-8">
                <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8 text-center md:text-left">
                  
              
                  <div>
                    <h2 className="text-xl font-bold mb-2">Interview Yodha</h2>
                    <p className="text-sm">Your go-to platform to prepare smartly for interviews.</p>
                  </div>

             
                  <div>
                    <h3 className="text-lg font-semibold mb-2">Quick Links</h3>
                    <ul className="space-y-1 text-sm">
                      <li><a href="/" className="hover:underline">Home</a></li>
                      <li><a href="/dashboard" className="hover:underline">Industry Insights</a></li>
                      <li><a href="/interview" className="hover:underline">Mock Interviews</a></li>
                      <li><a href="/resume" className="hover:underline">AI Resume Builder</a></li>
                      <li><a href="/ai-cover-letter" className="hover:underline">Ai Cover Letter</a></li>
                    </ul>
                  </div>

                
                  <div>
                    <h3 className="text-lg font-semibold mb-2">Connect With Us</h3>
                    <ul className="space-y-1 text-sm">
                      <li>Email: majorproject2025ahmnn@gmail.com</li>
                      <li>LinkedIn | Twitter | YouTube</li>
                    </ul>
                  </div>
                </div>

                {/* Bottom Bar */}
                <div className="mt-8 border-t border-gray-700 pt-4 text-sm text-center">
                  <p>&copy; {new Date().getFullYear()} Interview Yodha. All rights reserved.</p>
                </div>
              </footer>

            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
