

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import Link from 'next/link';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InterView Yodha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            <footer className="bg-muted/50 py-12">
              <footer className="bg-black text-gray-200 py-8">
                <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8 text-center md:text-left">
                  
              
                  <div>
                    <h2 className="text-xl font-bold mb-2">Interview Yodha</h2>
                    <p className="text-sm">Your go-to platform to prepare smartly for interviews.</p>
                  </div>

             
                  <div>
                    <h3 className="text-lg font-semibold mb-2">Quick Links</h3>
                    <ul className="space-y-1 text-sm">
                      <li>
                        <Link href="/" className="hover:underline">Home</Link>
                      </li>
                      <li>
                        <Link href="/dashboard" className="hover:underline">Industry Insights</Link>
                      </li>
                      <li>
                        <Link href="/interview" className="hover:underline">Mock Interviews</Link>
                      </li>
                      <li>
                        <Link href="/resume" className="hover:underline">AI Resume Builder</Link>
                      </li>
                      <li>
                        <Link href="/ai-cover-letter" className="hover:underline">AI Cover Letter</Link>
                      </li>
                    </ul>

                  </div>

                
                  <div>
                    <h3 className="text-lg font-semibold mb-2">Connect With Us</h3>
                    <ul className="space-y-1 text-sm">
                      <li>Email: majorproject2025ahmnn@gmail.com</li>
                      <li>LinkedIn | Twitter | YouTube</li>
                    </ul>
                  </div>
                </div>

                {/* Bottom Bar */}
                <div className="mt-8 border-t border-gray-700 pt-4 text-sm text-center">
                  <p>&copy; {new Date().getFullYear()} Interview Yodha. All rights reserved.</p>
                </div>
              </footer>

            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
